# Generated by Django 5.0.6 on 2026-07-30 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('government', 'Government'), ('developer', 'Developer')], max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('governorate', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=80)),
                ('district', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('announced', 'Announced'), ('open_for_booking', 'Open for Booking'), ('under_construction', 'Under Construction'), ('delivered', 'Delivered')], default='announced', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('cover_image', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='developers.developer')),
            ],
            options={
                'db_table': 'projects',
                'indexes': [models.Index(fields=['type', 'status'], name='idx_projects_type_status'), models.Index(fields=['governorate', 'city'], name='idx_projects_location')],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'developer'), ('developer__isnull', False)), models.Q(('type', 'government'), ('developer__isnull', True)), _connector='OR'), name='chk_project_developer'),
        ),
    ]
