# Generated by Django 5.0.6 on 2026-07-30 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('resale', 'Resale'), ('developer_unit', 'Developer Unit')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('floor', models.SmallIntegerField(blank=True, null=True)),
                ('finishing', models.CharField(blank=True, choices=[('core_shell', 'Core & Shell (طوب أحمر)'), ('semi', 'Semi Finished (نصف تشطيب)'), ('fully', 'Fully Finished (تشطيب كامل)'), ('lux', 'Lux / Super Lux (سوبر لوكس)')], max_length=12, null=True)),
                ('unit_attributes', models.JSONField(blank=True, default=dict)),
                ('governorate', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=80)),
                ('district', models.CharField(blank=True, max_length=80, null=True)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('negotiable', models.BooleanField(default=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('transfer_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('installment_plan', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('active', 'Active'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('archived', 'Archived')], default='draft', max_length=15)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='developer_listings', to='developers.developer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_listings', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resale_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listings',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=500)),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('floorplan', 'Floorplan')], default='photo', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='listings.listing')),
            ],
            options={
                'db_table': 'media',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'governorate', 'city'], name='idx_listings_search'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'asking_price'], name='idx_listings_price'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'bedrooms'], name='idx_listings_bedrooms'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['type', 'status'], name='idx_listings_type'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['project'], name='idx_listings_project'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'resale'), ('seller__isnull', False)), models.Q(('type', 'developer_unit'), ('developer__isnull', False), ('project__isnull', False)), _connector='OR'), name='chk_listing_owner'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['listing', 'sort_order'], name='idx_media_listing'),
        ),
    ]
