# Generated by Django 5.0.6 on 2026-08-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(upload_to='listings/%Y/%m/'),
        ),
    ]
