# Generated by Django 5.0.6 on 2026-08-28 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
        ('listings', '0002_alter_media_file_imagefield_add_is_primary'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='chk_listing_owner',
        ),
        migrations.AddField(
            model_name='listing',
            name='source_seller_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='source_seller_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='source_site',
            field=models.CharField(blank=True, choices=[('propertyfinder', 'Property Finder'), ('dubizzle', 'Dubizzle')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('resale', 'Resale'), ('developer_unit', 'Developer Unit'), ('scraped', 'Scraped from Web')], max_length=15),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'resale'), ('seller__isnull', False)), models.Q(('type', 'developer_unit'), ('developer__isnull', False), ('project__isnull', False)), models.Q(('type', 'scraped'), ('seller__isnull', False)), _connector='OR'), name='chk_listing_owner'),
        ),
    ]
