# Generated by Django 5.0.6 on 2026-08-31 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
        ('listings', '0004_listing_property_type'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='developer_current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='exit_commission_payer',
            field=models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='exit_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='exit_verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='exit_verification_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_exit_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner_confirmed_no_markup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='listings/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='kind',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('floorplan', 'Floorplan'), ('contract', 'Contract'), ('payment_receipt', 'Payment Receipt')], default='photo', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(check=models.Q(('is_exit_listing', False), ('type', 'resale'), _connector='OR'), name='chk_exit_listing_type'),
        ),
    ]
