# Generated by Django 5.0.6 on 2026-07-30 16:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('commercial_register_no', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.CharField(blank=True, max_length=500, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('commission_terms', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'developers',
            },
        ),
    ]
