# Generated by Django 5.0.6 on 2026-08-31 21:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contract_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('years_paid', models.DecimalField(decimal_places=2, max_digits=4)),
                ('computed_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'engagement_exit_leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
