# Generated by Django 5.0.6 on 2026-08-31 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0004_listing_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contract_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('years_paid', models.DecimalField(decimal_places=2, max_digits=4)),
                ('computed_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exit_leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExitListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('developer_current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('owner_confirmed_no_markup', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('commission_payer', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=1.25, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_profile', to='listings.listing')),
            ],
            options={
                'db_table': 'exit_listings',
            },
        ),
        migrations.CreateModel(
            name='ExitDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('contract', 'Contract'), ('payment_receipt', 'Payment Receipt'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='exit_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exit_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='exit_deals.exitlisting')),
            ],
            options={
                'db_table': 'exit_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
