// Values must stay in sync with Governorate in backend/apps/accounts/models.py
export const GOVERNORATES = [
  { value: 'cairo', ar: 'القاهرة', en: 'Cairo' },
  { value: 'giza', ar: 'الجيزة', en: 'Giza' },
  { value: 'alexandria', ar: 'الإسكندرية', en: 'Alexandria' },
  { value: 'qalyubia', ar: 'القليوبية', en: 'Qalyubia' },
  { value: 'sharqia', ar: 'الشرقية', en: 'Sharqia' },
  { value: 'dakahlia', ar: 'الدقهلية', en: 'Dakahlia' },
  { value: 'beheira', ar: 'البحيرة', en: 'Beheira' },
  { value: 'gharbia', ar: 'الغربية', en: 'Gharbia' },
  { value: 'monufia', ar: 'المنوفية', en: 'Monufia' },
  { value: 'kafr_el_sheikh', ar: 'كفر الشيخ', en: 'Kafr El Sheikh' },
  { value: 'damietta', ar: 'دمياط', en: 'Damietta' },
  { value: 'port_said', ar: 'بورسعيد', en: 'Port Said' },
  { value: 'ismailia', ar: 'الإسماعيلية', en: 'Ismailia' },
  { value: 'suez', ar: 'السويس', en: 'Suez' },
  { value: 'north_sinai', ar: 'شمال سيناء', en: 'North Sinai' },
  { value: 'south_sinai', ar: 'جنوب سيناء', en: 'South Sinai' },
  { value: 'red_sea', ar: 'البحر الأحمر', en: 'Red Sea' },
  { value: 'matrouh', ar: 'مطروح', en: 'Matrouh' },
  { value: 'new_valley', ar: 'الوادي الجديد', en: 'New Valley' },
  { value: 'fayoum', ar: 'الفيوم', en: 'Fayoum' },
  { value: 'beni_suef', ar: 'بني سويف', en: 'Beni Suef' },
  { value: 'minya', ar: 'المنيا', en: 'Minya' },
  { value: 'assiut', ar: 'أسيوط', en: 'Assiut' },
  { value: 'sohag', ar: 'سوهاج', en: 'Sohag' },
  { value: 'qena', ar: 'قنا', en: 'Qena' },
  { value: 'luxor', ar: 'الأقصر', en: 'Luxor' },
  { value: 'aswan', ar: 'أسوان', en: 'Aswan' },
];
