# Generated by Django 5.0.6 on 2026-07-30 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('collecting_docs', 'Collecting Documents'), ('ready', 'Ready for Submission'), ('submitted', 'Submitted to Government'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='collecting_docs', max_length=18)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applications',
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_apps_user'), models.Index(fields=['status'], name='idx_apps_status')],
            },
        ),
    ]
