# Generated by Django 5.0.6 on 2026-07-30 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=500)),
                ('kind', models.CharField(choices=[('rss', 'RSS Feed'), ('html', 'HTML Page'), ('api', 'REST API'), ('facebook_page', 'Facebook Page')], max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scrape_sources',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('source_url', models.CharField(max_length=700)),
                ('source_url_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending_review', max_length=15)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='projects.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='govfeed.scrapesource')),
            ],
            options={
                'db_table': 'announcements',
                'indexes': [models.Index(fields=['status', '-published_at'], name='idx_ann_status_pub')],
            },
        ),
    ]
