# Generated by Django 5.0.6 on 2026-09-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='requirements',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
