# Generated by Django 5.0.6 on 2026-09-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govfeed', '0003_seed_scrape_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='suggested_program_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
